### PR TITLE
print requires ( ) on python 3 - Updated README

### PR DESCRIPTION
**Pull request by rochacbruno**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks! Note that this project is dead, IIRC there is a fork somewhere, ideally the README should point people there.

**Comment by rochacbruno** [comment]
@gvanrossum ok, I'll try to find where the fork is located and send a PR including a link to README.

**Comment by rochacbruno** [comment]
I've found a @pyxl3 organization with a single project but it is outdated and behind yours, also you are the owner on PyPI.

If the project is not going to be maintained by you the suggestion would be adding more people as maintainer on PyPI and maybe giving push access to this same repository?

**Comment by gvanrossum** [comment]
No, *this* repo exists so that at Dropbox we can use mypy on files
containing pyxl code. You are free to fork it and distribute the fork (as
long as you follow Dropbox's license) but please name it something other
than pyxl3.

**Pull request merged**
